### ISSUE TITLE
Multiple lines not working

### ISSUE THREAD

**Issue by vikyd** [leftstick/vscode-string-transformer#1]
my code:
```js
'<a class="OpenPro" proid = "' + data_pro[i].f_pro_id + '" ' +
'   onclick="toOpenPro(this);" ' +
'   title="' + data_pro[i].f_pro_name + '" ' +
'   href="javascript:;">' +
'</a>'
```

It cannot convert to ES6 template string.

**Comment by leftstick** [comment]
@vikyd the implementation is not stable and not fully tested, please do not use it with your working env. 
And the solution currently i am using is not that elegant, i am thinking if it is possible to re-write it in next release. Feel free to give me PR if you have any better idea
